basePath: /
definitions:
  models.ErrorResponse:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  models.LoginBody:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.SignUpBody:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.SignUpResponse:
    properties:
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Readness API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Вход пользователя по почте и паролю
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginBody'
      produces:
      - application/json
      responses:
        "204":
          description: Токены установлены в cookie
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Вход
      tags:
      - Auth
  /auth/logout:
    post:
      description: Удаляет refresh-токен из БД и очищает cookie
      responses:
        "204":
          description: Cookie очищены
      summary: Выход
      tags:
      - Auth
  /auth/refresh:
    post:
      description: Выдаёт новый access-токен (в cookie) по refresh-токену из cookie
      produces:
      - application/json
      responses:
        "204":
          description: Новый access-токен установлен в cookie
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Обновление токена
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Регистрация пользователя по имени, почте и паролю
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUpBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignUpResponse'
        "400":
          description: Invalid request or validation error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Регистрация
      tags:
      - Auth
swagger: "2.0"
